services:
  app:
    build:
      context: .
      args:
        DOCKER_IMAGE: ${DOCKER_IMAGE}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
