from core.config import settings

BOT_PLAYER_CONFIG = {}
BOT_THINKING_MULTIPLIER = settings.BOT_THINKING_MULTIPLIER.split(", ")
BOT_ABILITY_USE_CHANCE = settings.BOT_ABILITY_USE_CHANCE.split(", ")
BOT_ACTION_INTERVAL_MULTIPLIER = settings.BOT_ACTION_INTERVAL_MULTIPLIER.split(", ")
BOT_DAMAGE_MULTIPLIER = settings.BOT_DAMAGE_MULTIPLIER.split(", ")

for i, diff in enumerate(["easy", "medium", "hard"]):
    BOT_PLAYER_CONFIG[diff] = {
        "thinking_multiplier": float(BOT_THINKING_MULTIPLIER[i]),
        "ability_use_chance": float(BOT_ABILITY_USE_CHANCE[i]),
        "action_interval_multiplier": float(BOT_ACTION_INTERVAL_MULTIPLIER[i]),
        "damage_multiplier": float(BOT_DAMAGE_MULTIPLIER[i]),
    }

DAMAGE_PER_PROBLEM = settings.PRACTICE_DAMAGE_PER_PROBLEM
MAJOR_DAMAGE_MIN = settings.PRACTICE_MAJOR_DAMAGE_MIN
MAJOR_DAMAGE_MAX = settings.PRACTICE_MAJOR_DAMAGE_MAX
MINOR_DAMAGE_MIN = settings.PRACTICE_MINOR_DAMAGE_MIN
MINOR_DAMAGE_MAX = settings.PRACTICE_MINOR_DAMAGE_MAX
HEALING_THRESHOLD = settings.PRACTICE_HEALING_THRESHOLD
HEAL_CHECK_INTERVAL = settings.PRACTICE_HEAL_CHECK_INTERVAL

BASE_ACTION_INTERVAL = settings.PRACTICE_ACTION_INTERVAL
MAX_ADDITIONAL_INTERVAL = settings.PRACTICE_ADDITIONAL_INTERVAL
READING_SPEED = settings.PRACTICE_READING_SPEED
BASE_THINKING_TIME = settings.PRACTICE_THINKING_TIME

BOT_NAME = "Quack"
