name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Setup environment file
      run: cp .env.example .env

    - name: Build Docker image
      run: |
        docker build -t beatcode-python ./docker/python/
        docker build -t beatcode-java ./docker/java/
        docker build -t beatcode-cpp ./docker/cpp/
      working-directory: ./app

    - name: Run unit tests
      run: |
        cd app
        pytest tests/unit